title: Artrointel's blog
description: > # this means to ignore newlines until "baseurl:"
  The story of a developer who will change the world.
  Neural Network, Graphics and everything to change the world.
  This codename is Artrointel.
permalink: ':title/'
baseurl: "/artrointel" # the subpath of your site, e.g. /blog
url: "https://artrointel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Woohyun Kim # add your name
author-img: main_picture.jpg # add your photo
about-author: I am a software developer focusing on both AI and graphics. Cannot just leave without coding.
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: artrointel # add your Github handle
linkedin: # add your Linkedin handle
email: artrointel@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
